domain:
  boundaries:
    max:
    - 500.0
    - 500.0
    - 500.0
    min:
    - -500.0
    - -500.0
    - -500.0
    step: 20.0
  drag_coefficient: 7.5
  use_2d: true
interactions:
  cylinder_cylinder_adhesion: 10.0
  cylinder_cylinder_repulsion: 20.0
  cylinder_cylinder_smoothness: 1.5
  sphere_cylinder_adhesion: 15.0
  sphere_cylinder_repulsion: 50.0
  sphere_cylinder_smoothness: 1.5
  sphere_sphere_adhesion: 10.0
  sphere_sphere_repulsion: 30.0
  sphere_sphere_smoothness: 1.5
  type: potentials
neurons:
  clocks:
    death_rate: 0.0001
    differentiation_rate: 0.001
    proliferation_rate: 0.001
  max_number_of_neurites: 4
  objects:
    cell_interaction_factor: 1.0
    cell_radius: 5.0
    neurite_default_length: 20.0
    neurite_interaction_factor: 0.8
    neurite_radius: 0.5
    neurite_spring_constant: 10.0
time:
  step: 0.3
  total_time: 1000.0
